version: '3.8'

services:
  api-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-monitor
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs