services:
  api-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-monitor
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor-worker
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["node", "dist/queues/monitorWorker.js"] 
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    
